
import React from 'react'


export const Stock_list=()=>{

    const stock_list=[
    {'ticker': 'MMM', 'name': 'スリーエム'},
    {'ticker': 'MMM', 'name': '3M'},
    {'ticker': 'ABT', 'name': 'Abbott Laboratories'},
    {'ticker': 'ABBV', 'name': 'AbbVie'},
    {'ticker': 'ABMD', 'name': 'Abiomed'},
    {'ticker': 'ACN', 'name': 'Accenture'},
    {'ticker': 'ATVI', 'name': 'Activision Blizzard'},
    {'ticker': 'ADM', 'name': 'ADM'},
    {'ticker': 'ADBE', 'name': 'Adobe'},
    {'ticker': 'AAP', 'name': 'Advance Auto Parts'},
    {'ticker': 'AMD', 'name': 'Advanced Micro Devices'},
    {'ticker': 'AES', 'name': 'AES Corp'},
    {'ticker': 'AFL', 'name': 'Aflac'},
    {'ticker': 'A', 'name': 'Agilent Technologies'},
    {'ticker': 'APD', 'name': 'Air Products & Chemicals'},
    {'ticker': 'AKAM', 'name': 'Akamai Technologies'},
    {'ticker': 'ALK', 'name': 'Alaska Air Group'},
    {'ticker': 'ARE', 'name': 'Alexandria Real Estate Equities'},
    {'ticker': 'ALB', 'name': 'Albemarle Corporation'},
    {'ticker': 'ALXN', 'name': 'Alexion Pharmaceuticals'},
    {'ticker': 'ALGN', 'name': 'Align Technology'},
    {'ticker': 'ALLE', 'name': 'Allegion'},
    {'ticker': 'LNT', 'name': 'Alliant Energy'},
    {'ticker': 'ALL', 'name': 'Allstate Corp'},
    {'ticker': 'GOOGL', 'name': 'Alphabet (Class A)'},
    {'ticker': 'GOOG', 'name': 'Alphabet (Class C)'},
    {'ticker': 'MO', 'name': 'Altria Group'},
    {'ticker': 'AMZN', 'name': 'Amazon'},
    {'ticker': 'AMCR', 'name': 'Amco'},
    {'ticker': 'AEE', 'name': 'Ameren Corp'},
    {'ticker': 'AAL', 'name': 'American Airlines Group'},
    {'ticker': 'AEP', 'name': 'American Electric Power'},
    {'ticker': 'AXP', 'name': 'American Express'},
    {'ticker': 'AIG', 'name': 'American International Group'},
    {'ticker': 'AMT', 'name': 'American Tower'},
    {'ticker': 'AWK', 'name': 'American Water Works'},
    {'ticker': 'AMP', 'name': 'Ameriprise Financial'},
    {'ticker': 'ABC', 'name': 'AmerisourceBergen'},
    {'ticker': 'AME', 'name': 'Ametek'},
    {'ticker': 'AMGN', 'name': 'Amgen'},
    {'ticker': 'APH', 'name': 'Amphenol Corp'},
    {'ticker': 'ADI', 'name': 'Analog Devices'},
    {'ticker': 'ANSS', 'name': 'Ansys'},
    {'ticker': 'ANTM', 'name': 'Anthem'},
    {'ticker': 'AOS', 'name': 'AO Smith'},
    {'ticker': 'AON', 'name': 'Aon'},
    {'ticker': 'APA', 'name': 'APA Corporation'},
    {'ticker': 'AAPL', 'name': 'Apple'},
    {'ticker': 'AMAT', 'name': 'Applied Materials'},
    {'ticker': 'APTV', 'name': 'Aptiv'},
    {'ticker': 'ANET', 'name': 'Arista Networks'},
    {'ticker': 'AJG', 'name': 'Arthur J. Gallagher & Co.'},
    {'ticker': 'AIZ', 'name': 'Assurant'},
    {'ticker': 'T', 'name': 'AT&T'},
    {'ticker': 'ATO', 'name': 'Atmos Energy'},
    {'ticker': 'ADSK', 'name': 'Autodesk'},
    {'ticker': 'ADP', 'name': 'Automatic Data Processing'},
    {'ticker': 'AZO', 'name': 'AutoZone'},
    {'ticker': 'AVB', 'name': 'AvalonBay Communities'},
    {'ticker': 'AVY', 'name': 'Avery Dennison'},
    {'ticker': 'BKR', 'name': 'Baker Hughes'},
    {'ticker': 'BLL', 'name': 'Ball Corp'},
    {'ticker': 'BAC', 'name': 'Bank of America'},
    {'ticker': 'BAX', 'name': 'Baxter International'},
    {'ticker': 'BDX', 'name': 'Becton Dickinson'},
  
    {'ticker': 'BBY', 'name': 'Best Buy'},
    {'ticker': 'BIO', 'name': 'Bio-Rad Laboratories'},
    {'ticker': 'BIIB', 'name': 'Biogen'},
    {'ticker': 'BLK', 'name': 'BlackRock'},
    {'ticker': 'BK', 'name': 'BNY Mellon'},
    {'ticker': 'BA', 'name': 'Boeing Company'},
    {'ticker': 'BKNG', 'name': 'Booking Holdings'},
    {'ticker': 'BWA', 'name': 'BorgWarner'},
    {'ticker': 'BXP', 'name': 'Boston Properties'},
    {'ticker': 'BSX', 'name': 'Boston Scientific'},
    {'ticker': 'BMY', 'name': 'Bristol-Myers Squibb'},
    {'ticker': 'AVGO', 'name': 'Broadcom'},
    {'ticker': 'BR', 'name': 'Broadridge Financial Solutions'},
    
    {'ticker': 'CHRW', 'name': 'C. H. Robinson'},
    {'ticker': 'COG', 'name': 'Cabot Oil & Gas'},
    {'ticker': 'CDNS', 'name': 'Cadence Design Systems'},
    {'ticker': 'CZR', 'name': 'Caesars Entertainment'},
    {'ticker': 'CPB', 'name': 'Campbell Soup'},
    {'ticker': 'COF', 'name': 'Capital One Financial'},
    {'ticker': 'CAH', 'name': 'Cardinal Health'},
    {'ticker': 'KMX', 'name': 'CarMax'},
    {'ticker': 'CCL', 'name': 'Carnival Corporation'},
    {'ticker': 'CARR', 'name': 'Carrier Global'},
    {'ticker': 'CTLT', 'name': 'Catalent'},
    {'ticker': 'CAT', 'name': 'Caterpillar'},
    {'ticker': 'CBOE', 'name': 'Cboe Global Markets'},
    {'ticker': 'CBRE', 'name': 'CBRE'},
    {'ticker': 'CDW', 'name': 'CDW'},
    {'ticker': 'CE', 'name': 'Celanese'},
    {'ticker': 'CNC', 'name': 'Centene Corporation'},
    {'ticker': 'CNP', 'name': 'CenterPoint Energy'},
    {'ticker': 'CERN', 'name': 'Cerner'},
    {'ticker': 'CF', 'name': 'CF Industries'},
    {'ticker': 'CRL', 'name': 'Charles River Laboratories'},
    {'ticker': 'SCHW', 'name': 'Charles Schwab Corporation'},
    {'ticker': 'CHTR', 'name': 'Charter Communications'},
    {'ticker': 'CVX', 'name': 'Chevron Corporation'},
    {'ticker': 'CMG', 'name': 'Chipotle Mexican Grill'},
    {'ticker': 'CB', 'name': 'Chubb'},
    {'ticker': 'CHD', 'name': 'Church & Dwight'},
    {'ticker': 'CI', 'name': 'Cigna'},
    {'ticker': 'CINF', 'name': 'Cincinnati Financial'},
    {'ticker': 'CTAS', 'name': 'Cintas Corporation'},
    {'ticker': 'CSCO', 'name': 'Cisco Systems'},
    {'ticker': 'C', 'name': 'Citigroup'},
    {'ticker': 'CFG', 'name': 'Citizens Financial Group'},
    {'ticker': 'CTXS', 'name': 'Citrix Systems'},
    {'ticker': 'CLX', 'name': 'Clorox'},
    {'ticker': 'CME', 'name': 'CME Group'},
    {'ticker': 'CMS', 'name': 'CMS Energy'},
    {'ticker': 'KO', 'name': 'Coca-Cola Company'},
    {'ticker': 'CTSH', 'name': 'Cognizant Technology Solutions'},
    {'ticker': 'CL', 'name': 'Colgate-Palmolive'},
    {'ticker': 'CMCSA', 'name': 'Comcast'},
    {'ticker': 'CMA', 'name': 'Comerica'},
    {'ticker': 'CAG', 'name': 'Conagra Brands'},
    {'ticker': 'COP', 'name': 'ConocoPhillips'},
    {'ticker': 'ED', 'name': 'Consolidated Edison'},
    {'ticker': 'STZ', 'name': 'Constellation Brands'},
    {'ticker': 'CPRT', 'name': 'Copart'},
    {'ticker': 'GLW', 'name': 'Corning'},
    {'ticker': 'CTVA', 'name': 'Corteva'},
    {'ticker': 'COST', 'name': 'Costco'},
    {'ticker': 'CCI', 'name': 'Crown Castle'},
    {'ticker': 'CSX', 'name': 'CSX'},
    {'ticker': 'CMI', 'name': 'Cummins'},
    {'ticker': 'CVS', 'name': 'CVS Health'},
    {'ticker': 'DHI', 'name': 'D. R. Horton'},
    {'ticker': 'DHR', 'name': 'Danaher Corporation'},
    {'ticker': 'DRI', 'name': 'Darden Restaurants'},
    {'ticker': 'DVA', 'name': 'DaVita'},
    {'ticker': 'DE', 'name': 'Deere & Co.'},
    {'ticker': 'DAL', 'name': 'Delta Air Lines'},
    {'ticker': 'XRAY', 'name': 'Dentsply Sirona'},
    {'ticker': 'DVN', 'name': 'Devon Energy'},
    {'ticker': 'DXCM', 'name': 'DexCom'},
    {'ticker': 'FANG', 'name': 'Diamondback Energy'},
    {'ticker': 'DLR', 'name': 'Digital Realty Trust'},
    {'ticker': 'DFS', 'name': 'Discover Financial Services'},
    {'ticker': 'DISCA', 'name': 'Discovery (Series A)'},
    {'ticker': 'DISCK', 'name': 'Discovery (Series C)'},
    {'ticker': 'DISH', 'name': 'Dish Network'},
    {'ticker': 'DG', 'name': 'Dollar General'},
    {'ticker': 'DLTR', 'name': 'Dollar Tree'},
    {'ticker': 'D', 'name': 'Dominion Energy'},
    {'ticker': 'DPZ', 'name': "Domino's Pizza"},
    {'ticker': 'DOV', 'name': 'Dover Corporation'},
    {'ticker': 'DOW', 'name': 'Dow'},
    {'ticker': 'DTE', 'name': 'DTE Energy'},
    {'ticker': 'DUK', 'name': 'Duke Energy'},
    {'ticker': 'DRE', 'name': 'Duke Realty Corp'},
    {'ticker': 'DD', 'name': 'DuPont'},
    {'ticker': 'DXC', 'name': 'DXC Technology'},
    {'ticker': 'EMN', 'name': 'Eastman Chemical'},
    {'ticker': 'ETN', 'name': 'Eaton Corporation'},
    {'ticker': 'EBAY', 'name': 'eBay'},
    {'ticker': 'ECL', 'name': 'Ecolab'},
    {'ticker': 'EIX', 'name': 'Edison International'},
    {'ticker': 'EW', 'name': 'Edwards Lifesciences'},
    {'ticker': 'EA', 'name': 'Electronic Arts'},
    {'ticker': 'LLY', 'name': 'Eli Lilly & Co'},
    {'ticker': 'EMR', 'name': 'Emerson Electric Company'},
    {'ticker': 'ENPH', 'name': 'Enphase Energy'},
    {'ticker': 'ETR', 'name': 'Entergy'},
    {'ticker': 'EOG', 'name': 'EOG Resources'},
    {'ticker': 'EFX', 'name': 'Equifax'},
    {'ticker': 'EQIX', 'name': 'Equinix'},
    {'ticker': 'EQR', 'name': 'Equity Residential'},
    {'ticker': 'ESS', 'name': 'Essex Property Trust'},
    {'ticker': 'EL', 'name': 'Estée Lauder Companies'},
    {'ticker': 'ETSY', 'name': 'Etsy'},
    {'ticker': 'RE', 'name': 'Everest Re'},
    {'ticker': 'EVRG', 'name': 'Evergy'},
    {'ticker': 'ES', 'name': 'Eversource Energy'},
    {'ticker': 'EXC', 'name': 'Exelon'},
    {'ticker': 'EXPE', 'name': 'Expedia Group'},
    {'ticker': 'EXPD', 'name': 'Expeditors'},
    {'ticker': 'EXR', 'name': 'Extra Space Storage'},
    {'ticker': 'XOM', 'name': 'ExxonMobil'},
    {'ticker': 'FFIV', 'name': 'F5 Networks'},
    {'ticker': 'FB', 'name': 'Facebook'},
    {'ticker': 'FAST', 'name': 'Fastenal'},
    {'ticker': 'FRT', 'name': 'Federal Realty Investment Trust'},
    {'ticker': 'FDX', 'name': 'FedEx'},
    {'ticker': 'FIS', 'name': 'Fidelity National Information Services'},
    {'ticker': 'FITB', 'name': 'Fifth Third Bancorp'},
    {'ticker': 'FRC', 'name': 'First Republic Bank'},
    {'ticker': 'FE', 'name': 'FirstEnergy'},
    {'ticker': 'FISV', 'name': 'Fiserv'},
    {'ticker': 'FLT', 'name': 'Fleetcor'},
    {'ticker': 'FMC', 'name': 'FMC Corporation'},
    {'ticker': 'F', 'name': 'Ford'},
    {'ticker': 'FTNT', 'name': 'Fortinet'},
    {'ticker': 'FTV', 'name': 'Fortive'},
    {'ticker': 'FBHS', 'name': 'Fortune Brands Home & Security'},
    {'ticker': 'FOXA', 'name': 'Fox Corporation (Class A)'},
    {'ticker': 'FOX', 'name': 'Fox Corporation (Class B)'},
    {'ticker': 'BEN', 'name': 'Franklin Resources'},
    {'ticker': 'FCX', 'name': 'Freeport-McMoRan'},
    {'ticker': 'GPS', 'name': 'Gap'},
    {'ticker': 'GRMN', 'name': 'Garmin'},
    {'ticker': 'IT', 'name': 'Gartner'},
    {'ticker': 'GNRC', 'name': 'Generac Holdings'},
    {'ticker': 'GD', 'name': 'General Dynamics'},
    {'ticker': 'GE', 'name': 'General Electric'},
    {'ticker': 'GIS', 'name': 'General Mills'},
    {'ticker': 'GM', 'name': 'General Motors'},
    {'ticker': 'GPC', 'name': 'Genuine Parts'},
    {'ticker': 'GILD', 'name': 'Gilead Sciences'},
    {'ticker': 'GPN', 'name': 'Global Payments'},
    {'ticker': 'GL', 'name': 'Globe Life'},
    {'ticker': 'GS', 'name': 'Goldman Sachs'},
    {'ticker': 'HAL', 'name': 'Halliburton'},
    {'ticker': 'HBI', 'name': 'Hanesbrands'},
    {'ticker': 'HAS', 'name': 'Hasbro'},
    {'ticker': 'HCA', 'name': 'HCA Healthcare'},
    {'ticker': 'PEAK', 'name': 'Healthpeak Properties'},
    {'ticker': 'HSIC', 'name': 'Henry Schein'},
    {'ticker': 'HES', 'name': 'Hess Corporation'},
    {'ticker': 'HPE', 'name': 'Hewlett Packard Enterprise'},
    {'ticker': 'HLT', 'name': 'Hilton Worldwide'},
    {'ticker': 'HOLX', 'name': 'Hologic'},
    {'ticker': 'HD', 'name': 'Home Depot'},
    {'ticker': 'HON', 'name': 'Honeywell'},
    {'ticker': 'HRL', 'name': 'Hormel'},
    {'ticker': 'HST', 'name': 'Host Hotels & Resorts'},
    {'ticker': 'HWM', 'name': 'Howmet Aerospace'},
    {'ticker': 'HPQ', 'name': 'HP'},
    {'ticker': 'HUM', 'name': 'Humana'},
    {'ticker': 'HBAN', 'name': 'Huntington Bancshares'},
    {'ticker': 'HII', 'name': 'Huntington Ingalls Industries'},
    {'ticker': 'IBM', 'name': 'IBM'},
    {'ticker': 'IEX', 'name': 'IDEX Corporation'},
    {'ticker': 'IDXX', 'name': 'Idexx Laboratories'},
    {'ticker': 'INFO', 'name': 'IHS Markit'},
    {'ticker': 'ITW', 'name': 'Illinois Tool Works'},
    {'ticker': 'ILMN', 'name': 'Illumina'},
    {'ticker': 'INCY', 'name': 'Incyte'},
    {'ticker': 'IR', 'name': 'Ingersoll Rand'},
    {'ticker': 'INTC', 'name': 'Intel'},
    {'ticker': 'ICE', 'name': 'Intercontinental Exchange'},
    {'ticker': 'IFF', 'name': 'International Flavors & Fragrances'},
    {'ticker': 'IP', 'name': 'International Paper'},
    {'ticker': 'IPG', 'name': 'Interpublic Group'},
    {'ticker': 'INTU', 'name': 'Intuit'},
    {'ticker': 'ISRG', 'name': 'Intuitive Surgical'},
    {'ticker': 'IVZ', 'name': 'Invesco'},
    {'ticker': 'IPGP', 'name': 'IPG Photonics'},
    {'ticker': 'IQV', 'name': 'IQVIA'},
    {'ticker': 'IRM', 'name': 'Iron Mountain'},
    {'ticker': 'JKHY', 'name': 'Jack Henry & Associates'},
    {'ticker': 'J', 'name': 'Jacobs Engineering Group'},
    {'ticker': 'JBHT', 'name': 'JB Hunt'},
    {'ticker': 'SJM', 'name': 'JM Smucker'},
    {'ticker': 'JNJ', 'name': 'Johnson & Johnson'},
    {'ticker': 'JCI', 'name': 'Johnson Controls'},
    {'ticker': 'JPM', 'name': 'JPMorgan Chase'},
    {'ticker': 'JNPR', 'name': 'Juniper Networks'},
    {'ticker': 'KSU', 'name': 'Kansas City Southern'},
    {'ticker': 'K', 'name': "Kellogg's"},
    {'ticker': 'KEY', 'name': 'KeyCorp'},
    {'ticker': 'KEYS', 'name': 'Keysight Technologies'},
    {'ticker': 'KMB', 'name': 'Kimberly-Clark'},
    {'ticker': 'KIM', 'name': 'Kimco Realty'},
    {'ticker': 'KMI', 'name': 'Kinder Morgan'},
    {'ticker': 'KLAC', 'name': 'KLA Corporation'},
    {'ticker': 'KHC', 'name': 'Kraft Heinz'},
    {'ticker': 'KR', 'name': 'Kroger'},
    {'ticker': 'LB', 'name': 'L Brands'},
    {'ticker': 'LHX', 'name': 'L3Harris Technologies'},
    {'ticker': 'LH', 'name': 'LabCorp'},
    {'ticker': 'LRCX', 'name': 'Lam Research'},
    {'ticker': 'LW', 'name': 'Lamb Weston'},
    {'ticker': 'LVS', 'name': 'Las Vegas Sands'},
    {'ticker': 'LEG', 'name': 'Leggett & Platt'},
    {'ticker': 'LDOS', 'name': 'Leidos'},
    {'ticker': 'LEN', 'name': 'Lennar'},
    {'ticker': 'LNC', 'name': 'Lincoln National'},
    {'ticker': 'LIN', 'name': 'Linde'},
    {'ticker': 'LYV', 'name': 'Live Nation Entertainment'},
    {'ticker': 'LKQ', 'name': 'LKQ Corporation'},
    {'ticker': 'LMT', 'name': 'Lockheed Martin'},
    {'ticker': 'L', 'name': 'Loews Corporation'},
    {'ticker': 'LOW', 'name': "Lowe's"},
    {'ticker': 'LUMN', 'name': 'Lumen Technologies'},
    {'ticker': 'LYB', 'name': 'LyondellBasell'},
    {'ticker': 'MTB', 'name': 'M&T Bank'},
    {'ticker': 'MRO', 'name': 'Marathon Oil'},
    {'ticker': 'MPC', 'name': 'Marathon Petroleum'},
    {'ticker': 'MKTX', 'name': 'MarketAxess'},
    {'ticker': 'MAR', 'name': 'Marriott International'},
    {'ticker': 'MMC', 'name': 'Marsh & McLennan'},
    {'ticker': 'MLM', 'name': 'Martin Marietta Materials'},
    {'ticker': 'MAS', 'name': 'Masco'},
    {'ticker': 'MA', 'name': 'Mastercard'},
    {'ticker': 'MXIM', 'name': 'Maxim Integrated'},
    {'ticker': 'MKC', 'name': 'McCormick & Company'},
    {'ticker': 'MCD', 'name': "McDonald's"},
    {'ticker': 'MCK', 'name': 'McKesson Corporation'},
    {'ticker': 'MDT', 'name': 'Medtronic'},
    {'ticker': 'MRK', 'name': 'Merck & Co'},
    {'ticker': 'MET', 'name': 'MetLife'},
    {'ticker': 'MTD', 'name': 'Mettler Toledo'},
    {'ticker': 'MGM', 'name': 'MGM Resorts International'},
    {'ticker': 'MCHP', 'name': 'Microchip Technology'},
    {'ticker': 'MU', 'name': 'Micron Technology'},
    {'ticker': 'MSFT', 'name': 'Microsoft'},
    {'ticker': 'MAA', 'name': 'Mid-America Apartments'},
    {'ticker': 'MHK', 'name': 'Mohawk Industries'},
    {'ticker': 'TAP', 'name': 'Molson Coors Beverage Company'},
    {'ticker': 'MDLZ', 'name': 'Mondelez International'},
    {'ticker': 'MPWR', 'name': 'Monolithic Power Systems'},
    {'ticker': 'MNST', 'name': 'Monster Beverage'},
    {'ticker': 'MCO', 'name': "Moody's Corporation"},
    {'ticker': 'MS', 'name': 'Morgan Stanley'},
    {'ticker': 'MSI', 'name': 'Motorola Solutions'},
    {'ticker': 'MSCI', 'name': 'MSCI'},
    {'ticker': 'NDAQ', 'name': 'Nasdaq'},
    {'ticker': 'NTAP', 'name': 'NetApp'},
    {'ticker': 'NFLX', 'name': 'Netflix'},
    {'ticker': 'NWL', 'name': 'Newell Brands'},
    {'ticker': 'NEM', 'name': 'Newmont'},
    {'ticker': 'NWSA', 'name': 'News Corp (Class A)'},
    {'ticker': 'NWS', 'name': 'News Corp (Class B)'},
    {'ticker': 'NEE', 'name': 'NextEra Energy'},
    {'ticker': 'NLSN', 'name': 'Nielsen Holdings'},
    {'ticker': 'NKE', 'name': 'Nike'},
    {'ticker': 'NI', 'name': 'NiSource'},
    {'ticker': 'NSC', 'name': 'Norfolk Southern'},
    {'ticker': 'NTRS', 'name': 'Northern Trust'},
    {'ticker': 'NOC', 'name': 'Northrop Grumman'},
    {'ticker': 'NLOK', 'name': 'NortonLifeLock'},
    {'ticker': 'NCLH', 'name': 'Norwegian Cruise Line Holdings'},
    {'ticker': 'NOV', 'name': 'Nov'},
    {'ticker': 'NRG', 'name': 'NRG Energy'},
    {'ticker': 'NUE', 'name': 'Nucor'},
    {'ticker': 'NVDA', 'name': 'Nvidia'},
    {'ticker': 'NVR', 'name': 'NVR'},
    {'ticker': 'NXPI', 'name': 'NXP'},
    {'ticker': 'ORLY', 'name': "O'Reilly Automotive"},
    {'ticker': 'OXY', 'name': 'Occidental Petroleum'},
    {'ticker': 'ODFL', 'name': 'Old Dominion Freight Line'},
    {'ticker': 'OMC', 'name': 'Omnicom Group'},
    {'ticker': 'OKE', 'name': 'Oneok'},
    {'ticker': 'ORCL', 'name': 'Oracle'},
    {'ticker': 'OGN', 'name': 'Organon & Co.'},
    {'ticker': 'OTIS', 'name': 'Otis Worldwide'},
    {'ticker': 'PCAR', 'name': 'Paccar'},
    {'ticker': 'PKG', 'name': 'Packaging Corporation of America'},
    {'ticker': 'PH', 'name': 'Parker-Hannifin'},
    {'ticker': 'PAYX', 'name': 'Paychex'},
    {'ticker': 'PAYC', 'name': 'Paycom'},
    {'ticker': 'PYPL', 'name': 'PayPal'},
    {'ticker': 'PENN', 'name': 'Penn National Gaming'},
    {'ticker': 'PNR', 'name': 'Pentair'},
    {'ticker': 'PBCT', 'name': "People's United Financial"},
    {'ticker': 'PEP', 'name': 'PepsiCo'},
    {'ticker': 'PKI', 'name': 'PerkinElmer'},
    {'ticker': 'PRGO', 'name': 'Perrigo'},
    {'ticker': 'PFE', 'name': 'Pfizer'},
    {'ticker': 'PM', 'name': 'Philip Morris International'},
    {'ticker': 'PSX', 'name': 'Phillips 66'},
    {'ticker': 'PNW', 'name': 'Pinnacle West Capital'},
    {'ticker': 'PXD', 'name': 'Pioneer Natural Resources'},
    {'ticker': 'PNC', 'name': 'PNC Financial Services'},
    {'ticker': 'POOL', 'name': 'Pool Corporation'},
    {'ticker': 'PPG', 'name': 'PPG Industries'},
    {'ticker': 'PPL', 'name': 'PPL'},
    {'ticker': 'PFG', 'name': 'Principal Financial Group'},
    {'ticker': 'PG', 'name': 'Procter & Gamble'},
    {'ticker': 'PGR', 'name': 'Progressive Corporation'},
    {'ticker': 'PLD', 'name': 'Prologis'},
    {'ticker': 'PRU', 'name': 'Prudential Financial'},
    {'ticker': 'PTC', 'name': 'PTC'},
    {'ticker': 'PEG', 'name': 'Public Service Enterprise Group'},
    {'ticker': 'PSA', 'name': 'Public Storage'},
    {'ticker': 'PHM', 'name': 'PulteGroup'},
    {'ticker': 'PVH', 'name': 'PVH'},
    {'ticker': 'QRVO', 'name': 'Qorvo'},
    {'ticker': 'QCOM', 'name': 'Qualcomm'},
    {'ticker': 'PWR', 'name': 'Quanta Services'},
    {'ticker': 'DGX', 'name': 'Quest Diagnostics'},
    {'ticker': 'RL', 'name': 'Ralph Lauren Corporation'},
    {'ticker': 'RJF', 'name': 'Raymond James Financial'},
    {'ticker': 'RTX', 'name': 'Raytheon Technologies'},
    {'ticker': 'O', 'name': 'Realty Income Corporation'},
    {'ticker': 'REG', 'name': 'Regency Centers'},
    {'ticker': 'REGN', 'name': 'Regeneron Pharmaceuticals'},
    {'ticker': 'RF', 'name': 'Regions Financial Corporation'},
    {'ticker': 'RSG', 'name': 'Republic Services'},
    {'ticker': 'RMD', 'name': 'ResMed'},
    {'ticker': 'RHI', 'name': 'Robert Half International'},
    {'ticker': 'ROK', 'name': 'Rockwell Automation'},
    {'ticker': 'ROL', 'name': 'Rollins'},
    {'ticker': 'ROP', 'name': 'Roper Technologies'},
    {'ticker': 'ROST', 'name': 'Ross Stores'},
    {'ticker': 'RCL', 'name': 'Royal Caribbean Group'},
    {'ticker': 'SPGI', 'name': 'S&P Global'},
    {'ticker': 'CRM', 'name': 'Salesforce'},
    {'ticker': 'SBAC', 'name': 'SBA Communications'},
    {'ticker': 'SLB', 'name': 'Schlumberger'},
    {'ticker': 'STX', 'name': 'Seagate Technology'},
    {'ticker': 'SEE', 'name': 'Sealed Air'},
    {'ticker': 'SRE', 'name': 'Sempra Energy'},
    {'ticker': 'NOW', 'name': 'ServiceNow'},
    {'ticker': 'SHW', 'name': 'Sherwin-Williams'},
    {'ticker': 'SPG', 'name': 'Simon Property Group'},
    {'ticker': 'SWKS', 'name': 'Skyworks Solutions'},
    {'ticker': 'SNA', 'name': 'Snap-on'},
    {'ticker': 'SO', 'name': 'Southern Company'},
    {'ticker': 'LUV', 'name': 'Southwest Airlines'},
    {'ticker': 'SWK', 'name': 'Stanley Black & Decker'},
    {'ticker': 'SBUX', 'name': 'Starbucks'},
    {'ticker': 'STT', 'name': 'State Street Corporation'},
    {'ticker': 'STE', 'name': 'Steris'},
    {'ticker': 'SYK', 'name': 'Stryker Corporation'},
    {'ticker': 'SIVB', 'name': 'SVB Financial'},
    {'ticker': 'SYF', 'name': 'Synchrony Financial'},
    {'ticker': 'SNPS', 'name': 'Synopsys'},
    {'ticker': 'SYY', 'name': 'Sysco'},
    {'ticker': 'TMUS', 'name': 'T-Mobile US'},
    {'ticker': 'TROW', 'name': 'T. Rowe Price'},
    {'ticker': 'TTWO', 'name': 'Take-Two Interactive'},
    {'ticker': 'TPR', 'name': 'Tapestry'},
    {'ticker': 'TGT', 'name': 'Target Corporation'},
    {'ticker': 'TEL', 'name': 'TE Connectivity'},
    {'ticker': 'TDY', 'name': 'Teledyne Technologies'},
    {'ticker': 'TFX', 'name': 'Teleflex'},
    {'ticker': 'TER', 'name': 'Teradyne'},
    {'ticker': 'TSLA', 'name': 'Tesla'},
    {'ticker': 'TXN', 'name': 'Texas Instruments'},
    {'ticker': 'TXT', 'name': 'Textron'},
    {'ticker': 'COO', 'name': 'The Cooper Companies'},
    {'ticker': 'HIG', 'name': 'The Hartford'},
    {'ticker': 'HSY', 'name': 'The Hershey Company'},
    {'ticker': 'MOS', 'name': 'The Mosaic Company'},
    {'ticker': 'TRV', 'name': 'The Travelers Companies'},
    {'ticker': 'DIS', 'name': 'The Walt Disney Company'},
    {'ticker': 'TMO', 'name': 'Thermo Fisher Scientific'},
    {'ticker': 'TJX', 'name': 'TJX Companies'},
    {'ticker': 'TSCO', 'name': 'Tractor Supply Company'},
    {'ticker': 'TT', 'name': 'Trane Technologies'},
    {'ticker': 'TDG', 'name': 'TransDigm Group'},
    {'ticker': 'TRMB', 'name': 'Trimble'},
    {'ticker': 'TFC', 'name': 'Truist Financial'},
    {'ticker': 'TWTR', 'name': 'Twitter'},
    {'ticker': 'TYL', 'name': 'Tyler Technologies'},
    {'ticker': 'TSN', 'name': 'Tyson Foods'},
    {'ticker': 'UDR', 'name': 'UDR'},
    {'ticker': 'ULTA', 'name': 'Ulta Beauty'},
    {'ticker': 'UAA', 'name': 'Under Armour (Class A)'},
    {'ticker': 'UA', 'name': 'Under Armour (Class C)'},
    {'ticker': 'UNP', 'name': 'Union Pacific'},
    {'ticker': 'UAL', 'name': 'United Airlines'},
    {'ticker': 'UPS', 'name': 'United Parcel Service'},
    {'ticker': 'URI', 'name': 'United Rentals'},
    {'ticker': 'UNH', 'name': 'UnitedHealth Group'},
    {'ticker': 'UHS', 'name': 'Universal Health Services'},
    {'ticker': 'UNM', 'name': 'Unum Group'},
    {'ticker': 'USB', 'name': 'US Bancorp'},
    {'ticker': 'VLO', 'name': 'Valero Energy'},
    {'ticker': 'VTR', 'name': 'Ventas'},
    {'ticker': 'VRSN', 'name': 'Verisign'},
    {'ticker': 'VRSK', 'name': 'Verisk Analytics'},
    {'ticker': 'VZ', 'name': 'Verizon Communications'},
    {'ticker': 'VRTX', 'name': 'Vertex Pharmaceuticals'},
    {'ticker': 'VFC', 'name': 'VF Corporation'},
    {'ticker': 'VIAC', 'name': 'ViacomCBS'},
    {'ticker': 'VTRS', 'name': 'Viatris'},
    {'ticker': 'V', 'name': 'Visa'},
    {'ticker': 'VNO', 'name': 'Vornado Realty Trust'},
    {'ticker': 'VMC', 'name': 'Vulcan Materials'},
    {'ticker': 'WRB', 'name': 'W. R. Berkley Corporation'},
    {'ticker': 'WAB', 'name': 'Wabtec'},
    {'ticker': 'WBA', 'name': 'Walgreens Boots Alliance'},
    {'ticker': 'WMT', 'name': 'Walmart'},
    {'ticker': 'WM', 'name': 'Waste Management'},
    {'ticker': 'WAT', 'name': 'Waters Corporation'},
    {'ticker': 'WEC', 'name': 'WEC Energy Group'},
    {'ticker': 'WFC', 'name': 'Wells Fargo'},
    {'ticker': 'WELL', 'name': 'Welltower'},
    {'ticker': 'WST', 'name': 'West Pharmaceutical Services'},
    {'ticker': 'WDC', 'name': 'Western Digital'},
    {'ticker': 'WU', 'name': 'Western Union'},
    {'ticker': 'WRK', 'name': 'WestRock'},
    {'ticker': 'WY', 'name': 'Weyerhaeuser'},
    {'ticker': 'WHR', 'name': 'Whirlpool Corporation'},
    {'ticker': 'WMB', 'name': 'Williams Companies'},
    {'ticker': 'WLTW', 'name': 'Willis Towers Watson'},
    {'ticker': 'GWW', 'name': 'WW Grainger'},
    {'ticker': 'WYNN', 'name': 'Wynn Resorts'},
    {'ticker': 'XEL', 'name': 'Xcel Energy'},
    {'ticker': 'XLNX', 'name': 'Xilinx'},
    {'ticker': 'XYL', 'name': 'Xylem'},
    {'ticker': 'YUM', 'name': 'Yum! Brands'},
    {'ticker': 'ZBRA', 'name': 'Zebra Technologies'},
    {'ticker': 'ZBH', 'name': 'Zimmer Biomet'},
    {'ticker': 'ZION', 'name': 'Zions Bancorp'},
    {'ticker': 'ZTS', 'name': 'Zoetis'},
    {'ticker': 'BIDU', 'name': 'Baidu.com, Inc.'},
    {'ticker': 'CELG', 'name': 'Celgene Corporation'},
    {'ticker': 'SIRI', 'name': 'Sirius XM Radio, Inc.'},
    {'ticker': 'WDAY', 'name': 'Workday, Inc.'},
    {'ticker': 'JD', 'name': 'JD.com'},
    {'ticker': 'NTES', 'name': 'NetEase, Inc.'},
    {'ticker': 'CHKP', 'name': 'Check Point Software Technologies Ltd.'},
    {'ticker': 'BMRN', 'name': 'BioMarin Pharmaceutical, Inc.'},
    {'ticker': 'LULU', 'name': 'Lululemon athletica'},
    {'ticker': 'MYL', 'name': 'Mylan N.V.'},
    {'ticker': 'MELI', 'name': 'MercadoLibre'},
    {'ticker': 'CTRP', 'name': 'Ctrip International'},
    {'ticker': 'SYMC', 'name': 'Symantec Corporation'},
    {'ticker': 'LBTYK', 'name': 'Liberty Global'},
    {'ticker': 'ASML', 'name': 'ASML Holding'},
    {'ticker': 'LBTYA', 'name': 'Liberty Global'}]

    return stock_list


}